apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-service
  namespace: platform-demo
spec:
  selector:
    app: demo-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

